uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
env:
  SECRET_ID: ${{ secrets.SECRET_ID}}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  PATHS: "https://www.lgxblog.cn/"
  FLUSH_TYPE: "delete" # purge all